[[search_dirs]]
path = "~/Documents"
depth = 5

[[search_dirs]]
path = "~/Stuff/Programming"
depth = 5

[[search_dirs]]
path = "~/dotfiles"
depth = 5

[shortcuts]
# "" = "move_up"
# "tab" = "move_down"
